# Site settings
title: Npgsql
subtitle: ".NET Data Provider for PostgreSQL"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Npgsql is an open source ADO.NET Data Provider for PostgreSQL, it allows programs written in C#, Visual Basic, F# to access the PostgreSQL database server.
  It allows any program developed for .NET framework to access database server. It is implemented in 100% C# code. Works with PostgreSQL 9.x and above.

#baseurl: ""
#url: "http://www.npgsql.org"
baseurl: "/"
url: "http://npgsql.github.io"
permalink:   /:categories/:title/

twitter_username: jekyllrb
github_username:  jekyll

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-56130753-1

# Build settings
markdown: kramdown
